export const PRAYER_STARTED = "PRAYER_STARTED"
export const PRAYER_COMPLETED = "PRAYER_COMPLETED"
export const PRAYER_NOT_STARTED = "PRAYER_NOT_STARTED"

export const FETCH_TIME = "FETCH_TIME"

export const AUTH_START = "AUTH_START"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_SUCCESS = "AUTH_SUCCESS"

export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const FETCH_PRAYER_SUCCESS = "FETCH_PRAYER_SUCCESS"
export const FETCH_PRAYER_FAIL ="FETCH_PRAYER_FAIL"

export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS"
export const FETCH_NOTIFICATIONS_FAIL ="FETCH_NOTIFICATIONS_FAIL"

export const GET_EMAIL_SUCCESS = "GET_EMAIL_SUCCESS" 
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS"
export const FETCH_USER_PROFILE_FAIL = "FETCH_USER_PROFILE_FAIL"